# Generated by Django 4.1 on 2022-08-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_teacher_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homeworks',
            fields=[
                ('homework_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('fromg', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'homeworks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(default=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
        migrations.CreateModel(
            name='StudentClasses',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='demo.student')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacherassignedclass',
            fields=[
                ('class_field', models.OneToOneField(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='demo.classes')),
            ],
            options={
                'db_table': 'teacherassignedclass',
                'managed': False,
            },
        ),
    ]
